import winsound
import urllib
import webbrowser

startQuestion = input('Would you like to learn about France? y/n')
true = 'y'
if startQuestion == true:
    print("OK!")
    winsound.PlaySound('Für Elise (Piano version) (1).wav', winsound.SND_FILENAME|winsound.SND_ASYNC
                       )
    historyQuestion = input("Would you like to hear a breif history about the French Revolution? y/n")
    true = 'y'
    if historyQuestion == true:
        print("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _")
        print ("It all began in the year 1789, when the Revolution overthrew the monarchy")
        print("--------------------------------------------------------------------------")
        print("                                      _ ")
        print("                                     | | ")
        print(" _ __ ___   ___  _ __   __ _ _ __ ___| |__  _   _")
        print("| '_ ` _ \ / _ \| '_ \ / _` | '__/ __| '_ \| | | |")
        print("| | | | | | (_) | | | | (_| | | | (__| | | | |_| |")
        print("|_| |_| |_|\___/|_| |_|\__,_|_|  \___|_| |_|\__, |")
        print("                                             __/ |")
        print("                                            |___/ ")
        historyQuestion2 = input("Continue? y/n")
        if historyQuestion2 == 'y':
            print("Then the country began to face violent periods of political turmoil")
            print("            \                                           ___/________")
            print("       ___   )                    ,  @                    /    \  \"")
            print("    @___, \ /                  @__\  /\              @___/      \@/")
            print("   /\__,   |                  /\_, \/ /             /\__/        |")
            print("  / \    / @\                / \   (               / \ /        / \ ")
            print("_/__|___/___/_______________/__|____\_____________/__/__________|__\__")
            print("and then Napoleon took over as the new leader of France...")
            print("                 ________")
            print("                /        \'")
            print("             __/       (o)\_")
            print("            /     ______\\   \'")
            print("            |____/__  __\____|")
            print("               [  --~~--  ]")
            print("                |(  L   )| ")
            print("          ___----\  __  /----_")
            print("         /   |  < \____/ >   |   \'")
            print("        /    |   < \--/ >    |    \'")
            print("        ||||||    \ \/ /     ||||||")
            print("        |          \  /   o       |")
            print("        |     |     \/   === |    |")
            print("        |     |      |o  ||| |    |")
            print("        |     \______|   +#* |    |")
            print("        |            |o      |    |        Napoleon Bonaparte, (1769-1821).")
            print("         \           |      /     /")
            print("         |\__________|o    /     /")
            print("         |           |    /     /")
            continueQuestion = input("Would you like to play an interactive version of the history of the French Revolution? y/n")
            if continueQuestion == 'y':
                name = input("what is your name?")
                joinQuestion = input(name + ", there is a secret group trying to overthrow the monarchy. Do you want to join in?!! y/n")
                if joinQuestion == 'y':
                    print("One day as " + name + " is walking there is a violent protest that erupts in the town square!")
                    violentRevolt = input("Join in the violent protest or flee and go back home? y for join/ n for flee")
                    if violentRevolt == 'n':
                        print("You flee back home to saftey")
                        print("  []___")
                        print(" /    /\'")
                        print("/____/__\'")
                        print("|[][]||||")
                        print("|____ |_|")
                        print("          ")
                        writeQuestion = input(name + " you get the oppertunity to write an article to be published anonymously in favor of the revolt, will you do it? y/n ")
                        if writeQuestion == 'y':
                            print("(\ ")
                            print("\'\ ")
                            print(" \'\     __________  ")
                            print(" / '|   ()_________)")
                            print(" \ '/    \   ~~~~~~ \'")
                            print("   \       \ ~~~~~~   \'")
                            print("   ==).      \__________\'")
                            print("  (__)       ()__________)")
                            print("Congratulations! " + name + " you have helped fund the revolt")
                            print("Now the monarchy has been overthrown!")
                            print("╔═══╗─────────────╔╗───╔╗───╔╗")
                            print("║╔═╗║────────────╔╝╚╗──║║──╔╝╚╗")
                            print("║║─╚╬══╦═╗╔══╦═╦═╩╗╔╬╗╔╣║╔═╩╗╔╬╦══╦═╗╔══╗")
                            print("║║─╔╣╔╗║╔╗╣╔╗║╔╣╔╗║║║║║║║║╔╗║║╠╣╔╗║╔╗╣══╣")
                            print("║╚═╝║╚╝║║║║╚╝║║║╔╗║╚╣╚╝║╚╣╔╗║╚╣║╚╝║║║╠══║")
                            print("╚═══╩══╩╝╚╩═╗╠╝╚╝╚╩═╩══╩═╩╝╚╩═╩╩══╩╝╚╩══╝")
                            print("──────────╔═╝║")
                            webpageQuestion = input(name + "would you like to visit France?! y/n")
                            if webpageQuestion == 'y':
                                webbrowser.open('https://www.france.com/') 
                                
                    else:
                        print("You have been arrested for being apart of the violent revolt!")
                        print("┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼")
                        print("███▀▀▀██┼███▀▀▀███┼███▀█▄█▀███┼██▀▀▀")
                        print("██┼┼┼┼██┼██┼┼┼┼┼██┼██┼┼┼█┼┼┼██┼██┼┼┼")
                        print("██┼┼┼▄▄▄┼██▄▄▄▄▄██┼██┼┼┼▀┼┼┼██┼██▀▀▀")
                        print("██┼┼┼┼██┼██┼┼┼┼┼██┼██┼┼┼┼┼┼┼██┼██┼┼┼")
                        print("███▄▄▄██┼██┼┼┼┼┼██┼██┼┼┼┼┼┼┼██┼██▄▄▄")
                        print("┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼")
                        print("███▀▀▀███┼▀███┼┼██▀┼██▀▀▀┼██▀▀▀▀██▄┼")
                        print("██┼┼┼┼┼██┼┼┼██┼┼██┼┼██┼┼┼┼██┼┼┼┼┼██┼")
                        print("██┼┼┼┼┼██┼┼┼██┼┼██┼┼██▀▀▀┼██▄▄▄▄▄▀▀┼")
                        print("██┼┼┼┼┼██┼┼┼██┼┼█▀┼┼██┼┼┼┼██┼┼┼┼┼██┼")
                        print("███▄▄▄███┼┼┼─▀█▀┼┼─┼██▄▄▄┼██┼┼┼┼┼██▄")
                        
else:
    print("You should :(")
    quit()
